import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

// Internal (staff-facing) WhatsApp alerts -- admins and media buyers, not
// customers -- on the same global WhatsApp Business number already used
// for customer/delivery-agent payment messages. These are the time-
// sensitive ones (vs. email, which would carry the rest): low ad-account
// balance with an active campaign, a payment just confirmed, a funding
// request submitted or decided, a transfer sent or failed. Each recipient
// needs their own whatsapp_number set on their profile (Settings) --
// nothing sends if that's empty.
//
// None of these templates are created/approved in Meta's WhatsApp Manager
// yet, so every send here tries the template first, then falls back to a
// plain free-form text message with the same content. Free-form only
// delivers within the 24h window after the recipient's last message to the
// business number (WhatsApp's rule, not ours) -- so today, before template
// approval, an alert only reaches someone who has messaged the bot number
// recently. Once a template is approved, its send will simply start
// succeeding and the fallback stops being used, with no code change needed.
//
//   POST { type, ...params } where type is one of:
//     "low_balance"            { ad_account_id }
//     "payment_confirmed_admin" { order_id }
//     "fund_request_submitted" { fund_request_id }
//     "fund_request_decided"   { fund_request_id }
//     "transfer_result"        { fund_request_id }

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const WHATSAPP_TOKEN = Deno.env.get("BEOLIV_WHATSAPP_ACCESS_TOKEN") ?? "";
const WHATSAPP_PHONE_ID = Deno.env.get("BEOLIV_WHATSAPP_PHONE_NUMBER_ID") ?? "";
const META_GRAPH_BASE = "https://graph.facebook.com/v18.0";

// "low_balance_alert_v1": ⚠️ {{1}}'s ad account "{{2}}" balance is low: NGN {{3}} remaining, with active campaigns still running. Fund it soon to avoid your ads pausing.
const TPL_LOW_BALANCE = Deno.env.get("WHATSAPP_TPL_LOW_BALANCE") ?? "low_balance_alert_v1";
// "payment_confirmed_admin_v1": ✅ Payment confirmed: NGN {{1}} for {{2}}'s order, generated by {{3}}.
const TPL_PAYMENT_CONFIRMED_ADMIN = Deno.env.get("WHATSAPP_TPL_PAYMENT_CONFIRMED_ADMIN") ?? "payment_confirmed_admin_v1";
// "fund_request_submitted_v1": 💸 {{1}} requested NGN {{2}} in funding. Note: {{3}}
const TPL_FUND_REQUEST_SUBMITTED = Deno.env.get("WHATSAPP_TPL_FUND_REQUEST_SUBMITTED") ?? "fund_request_submitted_v1";
// "fund_request_decided_v1": Your funding request for NGN {{1}} was {{2}}.
const TPL_FUND_REQUEST_DECIDED = Deno.env.get("WHATSAPP_TPL_FUND_REQUEST_DECIDED") ?? "fund_request_decided_v1";
// "transfer_sent_v1": ✅ Your transfer of NGN {{1}} was sent successfully.
const TPL_TRANSFER_SENT = Deno.env.get("WHATSAPP_TPL_TRANSFER_SENT") ?? "transfer_sent_v1";
// "transfer_failed_v1": ❌ Your transfer of NGN {{1}} failed: {{2}}. Please try again.
const TPL_TRANSFER_FAILED = Deno.env.get("WHATSAPP_TPL_TRANSFER_FAILED") ?? "transfer_failed_v1";

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

function json(obj: unknown, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" } });
}

const fmt = (n: number) => new Intl.NumberFormat("en-NG").format(Number(n ?? 0));

async function sendTemplate(toPhone: string, templateName: string, bodyParams: string[]) {
  const res = await fetch(`${META_GRAPH_BASE}/${WHATSAPP_PHONE_ID}/messages`, {
    method: "POST",
    headers: { Authorization: `Bearer ${WHATSAPP_TOKEN}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      messaging_product: "whatsapp",
      to: toPhone,
      type: "template",
      template: { name: templateName, language: { code: "en" }, components: [{ type: "body", parameters: bodyParams.map((p) => ({ type: "text", text: p })) }] },
    }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.message || `WhatsApp template send failed (${templateName})`);
  return data;
}

async function sendText(toPhone: string, body: string) {
  const res = await fetch(`${META_GRAPH_BASE}/${WHATSAPP_PHONE_ID}/messages`, {
    method: "POST",
    headers: { Authorization: `Bearer ${WHATSAPP_TOKEN}`, "Content-Type": "application/json" },
    body: JSON.stringify({ messaging_product: "whatsapp", to: toPhone, type: "text", text: { body } }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error?.message || "WhatsApp text send failed");
  return data;
}

async function adminNumbers(companyId: string): Promise<string[]> {
  const { data } = await supabase.from("profiles").select("whatsapp_number").eq("company_id", companyId).in("role", ["owner", "admin"]).not("whatsapp_number", "is", null);
  return (data ?? []).map((p: any) => p.whatsapp_number).filter(Boolean);
}

async function buyerNumber(mediaBuyerId: string): Promise<string | null> {
  const { data } = await supabase.from("profiles").select("whatsapp_number").eq("media_buyer_id", mediaBuyerId).eq("role", "buyer").not("whatsapp_number", "is", null).maybeSingle();
  return data?.whatsapp_number ?? null;
}

// Template first (works once approved, required for a first-ever/outside-
// 24h contact); plain text as the fallback (works right now, but only
// within the 24h window after the recipient last messaged the bot).
async function sendToMany(phones: string[], template: string, params: string[], fallbackText: string) {
  const results: Record<string, string> = {};
  for (const phone of phones) {
    try {
      await sendTemplate(phone, template, params);
      results[phone] = "sent (template)";
      continue;
    } catch (templateErr: any) {
      try {
        await sendText(phone, fallbackText);
        results[phone] = "sent (text fallback)";
      } catch (textErr: any) {
        results[phone] = `error: template failed (${templateErr.message}); text fallback failed (${textErr.message})`;
      }
    }
  }
  return results;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", {
      headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey" },
    });
  }
  if (req.method !== "POST") return json({ error: "POST only" }, 405);
  if (!WHATSAPP_TOKEN || !WHATSAPP_PHONE_ID) return json({ error: "WhatsApp isn't configured yet." }, 500);

  try {
    const body = await req.json();
    const { type } = body;

    if (type === "low_balance") {
      const { data: acct } = await supabase.from("ad_accounts").select("id, name, nickname, balance_naira, company_id, media_buyer_id").eq("id", body.ad_account_id).maybeSingle();
      if (!acct) return json({ error: "Ad account not found" }, 404);
      const buyer = acct.media_buyer_id ? await supabase.from("media_buyers").select("name").eq("id", acct.media_buyer_id).maybeSingle().then((r) => r.data) : null;
      const recipients = [...(await adminNumbers(acct.company_id)), ...(acct.media_buyer_id ? [await buyerNumber(acct.media_buyer_id)].filter(Boolean) as string[] : [])];
      const acctLabel = acct.nickname || acct.name || "account";
      const results = await sendToMany(recipients, TPL_LOW_BALANCE, [buyer?.name || "Your", acctLabel, fmt(acct.balance_naira)],
        `⚠️ ${buyer?.name || "Your"} ad account "${acctLabel}" balance is low: NGN ${fmt(acct.balance_naira)} remaining, with active campaigns still running. Fund it soon to avoid your ads pausing.`);
      return json({ ok: true, results });
    }

    if (type === "payment_confirmed_admin") {
      const { data: order } = await supabase.from("orders").select("id, customer_name, order_value_naira, company_id, media_buyers(name)").eq("id", body.order_id).maybeSingle();
      if (!order) return json({ error: "Order not found" }, 404);
      const recipients = await adminNumbers(order.company_id);
      const buyerName = (order.media_buyers as any)?.name || "—";
      const results = await sendToMany(recipients, TPL_PAYMENT_CONFIRMED_ADMIN, [fmt(order.order_value_naira), order.customer_name || "a customer", buyerName],
        `✅ Payment confirmed: NGN ${fmt(order.order_value_naira)} for ${order.customer_name || "a customer"}'s order, generated by ${buyerName}.`);
      return json({ ok: true, results });
    }

    if (type === "fund_request_submitted") {
      const { data: fr } = await supabase.from("fund_requests").select("id, amount_naira, note, company_id, media_buyers(name)").eq("id", body.fund_request_id).maybeSingle();
      if (!fr) return json({ error: "Funding request not found" }, 404);
      const recipients = await adminNumbers(fr.company_id);
      const buyerName = (fr.media_buyers as any)?.name || "A buyer";
      const results = await sendToMany(recipients, TPL_FUND_REQUEST_SUBMITTED, [buyerName, fmt(fr.amount_naira), fr.note || "no note"],
        `💸 ${buyerName} requested NGN ${fmt(fr.amount_naira)} in funding. Note: ${fr.note || "(none)"}`);
      return json({ ok: true, results });
    }

    if (type === "fund_request_decided") {
      const { data: fr } = await supabase.from("fund_requests").select("id, amount_naira, status, media_buyer_id").eq("id", body.fund_request_id).maybeSingle();
      if (!fr) return json({ error: "Funding request not found" }, 404);
      const phone = fr.media_buyer_id ? await buyerNumber(fr.media_buyer_id) : null;
      if (!phone) return json({ ok: true, results: {} });
      const results = await sendToMany([phone], TPL_FUND_REQUEST_DECIDED, [fmt(fr.amount_naira), fr.status],
        `Your funding request for NGN ${fmt(fr.amount_naira)} was ${fr.status}.`);
      return json({ ok: true, results });
    }

    if (type === "transfer_result") {
      const { data: fr } = await supabase.from("fund_requests").select("id, amount_naira, status, transfer_error, media_buyer_id, company_id").eq("id", body.fund_request_id).maybeSingle();
      if (!fr) return json({ error: "Funding request not found" }, 404);
      const buyerPhone = fr.media_buyer_id ? await buyerNumber(fr.media_buyer_id) : null;
      const admins = await adminNumbers(fr.company_id);
      const recipients = [...(buyerPhone ? [buyerPhone] : []), ...admins];
      const ok = fr.status === "transferred";
      const results = await sendToMany(
        recipients,
        ok ? TPL_TRANSFER_SENT : TPL_TRANSFER_FAILED,
        ok ? [fmt(fr.amount_naira)] : [fmt(fr.amount_naira), fr.transfer_error || "unknown error"],
        ok ? `✅ Your transfer of NGN ${fmt(fr.amount_naira)} was sent successfully.` : `❌ Your transfer of NGN ${fmt(fr.amount_naira)} failed: ${fr.transfer_error || "unknown error"}. Please try again.`,
      );
      return json({ ok: true, results });
    }

    return json({ error: `Unknown type: ${type}` }, 400);
  } catch (err: any) {
    console.error("send-internal-whatsapp error:", err);
    return json({ error: err.message }, 500);
  }
});
